openapi: 3.0.0
info:
  title: VersApp
  description: API de gestión de aspectos diarios como vehículos personales, tareas, lista de la compra y entrenamientos.
  version: 0.0.1
servers:
  - url: http://dev.versapp.com/apiservice/v1
    description: Servidor de desarrollo
paths:
components:
  schemas:
    Workout:
      type: Object
      required:
        - id
        - title
      properties:
        id: integer
        format: int64
        example: 1
        title:
          type: string
          example: "Día A - Tren superior"
        description:
          type: string
          example: "Entrenamiento tren superior con Enfasis en las dominadas"